config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'about', to: 'pages#about', as: :about
  get 'village-of-hope', to: 'pages#village', as: :village
  get 'rrc', to: 'pages#rrc', as: :rrc
  get 'contact', to: 'pages#contact', as: :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def village
  end

  def rrc
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>WESOFOD</title>

    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="secondary-page-container">

  <%= image_tag "kids", class: 'secondary-image-banner' %>
  <div class="secondary-text">
    <h4 class="secondary-header">About</h4>
    <p class="text-justify">
      The Welfare Society for the Disabled (WESOFOD) is a local non-governmental organisation committed to improving the quality of life of persons with disabilities in Kambia District, Sierra Leone. The organisation was established in 2004 and was born as a result of the increasing number of persons with disabilities being abandoned and living a life of hopelessness. The organisation takes care of cross disabilities affected people: most of them are affected by polio, but there are also cases of blindness, albinism and results of accidents. It is nationally and internationally recognised and has represented Sierra Leone in international fora.
    </p>
    <p class="text-justify">
      WESOFOD realizes that the person with a disability has a useful hidden ability and aims to identify and improve this ability, while developing a friendly environment where this ability can be utilized to the fullest. The organisation was crucial during the Ebola crisis (which hit Kambia hard, due to its proximity with Guinea), and thanks also to funding from Children in Crisis, WESOFOD was able to take care of PWDs (people with disabilities), otherwise totally neglected in such a perilous context.
    </p>
    <p class="text-justify">
      <a href="/village" class="link">The Village of Hope</a> and the <a href="/rrc" class="link">Residential Rehabilitation Centre</a> (RRC) function as centres of aggregation for PWDs, where they can talk, share their feelings and thoughts, support each other and face together the social stigma that still surrounds them.
    </p>
  </div>

  <div class="joseph">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <div class="joseph-text">
          <h4 class="secondary-header">Joseph Kamara</h4>
          <p class="text-justify">
            Joseph is the founder of WESOFOD.
          </p>
        </div>
      </div>
      <div class="col-xs-12 col-md-6">
        <%= image_tag "joseph", class: 'joseph-image' %>
      </div>
    </div>
  </div>
</div>


<%= render 'shared/footer' %>

app/views/pages/contact.html.erb
<div class="d-none d-lg-block">
  <div class="contact-page-container-large">
    <div class="contact-page-content">

      <div class="contact-large">
        <div class="contact-page-text">
          <h4 class="secondary-header">Contact</h4>
          <p class="text-justify">
            <strong>Address:</strong> The Welfare Society for the Disabled, The Village of Hope, Bamoi Luma, Kambia District, Sierra Leone
          </p>
          <p>
            <strong>Email:</strong> disabilitynotinability@gmail.com
          <p>
            <strong>Phone number:</strong> +232 77 58 63 29 or +232 78 69 84 60
          </p>
          </p>
        </div>

        <div class="map-container-large">
          <div id='map-large'></div>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="contact-page-container d-lg-none">

  <div class="contact-page-content">

    <div class="contact-small-screen">
      <div class="contact-page-text">
        <h4 class="secondary-header">Contact</h4>
        <p class="text-justify">
         <strong>Address:</strong> The Welfare Society for the Disabled, The Village of Hope, Bamoi Luma, Kambia District, Sierra Leone
        </p>
        <p>
          <strong>Email:</strong> disabilitynotinability@gmail.com
        <p>
          <strong>Phone number:</strong> +232 77 58 63 29
        </p>
        </p>
      </div>

      <div class="map-container">
        <div id='map'></div>
      </div>
    </div>

  </div>
</div>

<%= render 'shared/footer' %>

<%= javascript_pack_tag "map" %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="text-box d-none d-sm-block">
    <p>
      The Welfare Society for the Disabled (WESOFOD) is a local NGO committed to improving the quality of lives of persons with disabilities in Kambia District, Sierra Leone
    </p>
    <div class="read-more">
      <%= link_to 'READ MORE', about_path, class: 'button read-more-button' %>
    </div>
  </div>
</div>

<div class="home-container">

  <div class="home-text">
    <h1>The Welfare Society for the Disabled</h1>
    <p>
      The Welfare Society for the Disabled (WESOFOD) is a local non-governmental organisation run by and for people with disabilities. We fight for the <strong>rights of disabled people</strong> and for the children under our care. In Sierra Leone, children are left out of school because of their disability or background. We give these forgotten children a school, a home, and a future. We encourage these children to <strong>focus on their abilities</strong>, not their disabilities.
    </p>
  </div>

  <div class="home-images">
    <div class="row">
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "mary-walk", class: 'home-image' %>
      </div>
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "boy-in-chair", class: 'home-image' %>
      </div>
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "football", class: 'home-image' %>
      </div>
    </div>
  </div>

</div>

<%= render 'shared/footer' %>

app/views/pages/rrc.html.erb
<div class="secondary-page-container">

  <%= image_tag "rrc-1", class: 'secondary-image-banner' %>
  <div class="secondary-text">
    <h4 class="secondary-header">The Residential Rehabilitation Centre</h4>
    <p class="text-justify">
      In Kambia Town, thanks to Children in Crisis’ funding, WESOFOD manages the RRC, a centre that welcomes and homes CWDs (children with disabilities) who have been abandoned by their families and would otherwise be alone in the street.
    </p>
    <p class="text-justify">
      In this very rural and isolated region, disabled children often face the indignity of being carried into and out of public buildings, or having to go into the bush when they need the toilet.
    </p>
    <p class="text-justify">
      The RRC has been built to give as much independence as possible. The doorways are wide and there are ramps into and out of the building to accommodate mobility aides. The toilets are disabled-access, the children each have a bed of their own, and the plumbing infrastructure means that the children no longer have to struggle getting water from the well every day.
    </p>
    <p class="text-justify">
      Having a home which offers such basic freedoms means so much to these children.
    </p>
  </div>

  <div class="secondary-text rrc-secondary-text">
    <h4 class="secondary-header">3rd Year Anniversary Celebrations</h4>
    <div class="row">
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "3rd-year-football", class: 'home-image' %>
      </div>
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "microphone", class: 'home-image' %>
      </div>
      <div class="col-xs-offset-1 col-xs-12 col-md-4">
        <%= image_tag "talking", class: 'home-image' %>
      </div>
    </div>
    <%= image_tag "3rd-year-wide", class: 'rrc-image' %>
  </div>


</div>

<%= render 'shared/footer' %>

app/views/pages/village.html.erb
<div class="secondary-page-container">

  <%= image_tag "village-of-hope", class: 'secondary-image-banner' %>

  <div class="secondary-text">
    <div class="village-text">
      <h4 class="secondary-header">The Village of Hope</h4>
      <div class="village-image d-none d-sm-block"></div>
      <!-- <img src="app/assets/images/wesofod-new.jpeg" class="village-image"> -->
      <p class="text-justify">
        The Village of Hope is a residential, training, working and marketing centre for disabled people and their families. It homes over 75 people in total.
      </p>
      <p class="text-justify">
        There are several active shops and workshops in the Village including a carpenter, a coal-pot maker, a blacksmith, a tailor, and a wheelchair and crutch production and repair shop.
      </p>
      <p class="text-justify">
        A small section of the Village dates back to the 1990s, before the civil war interrupted all activities. Recently, thanks to a six-month project ending in March 2019 with Trocaire - an Irish charity - the Village has been provided with funds to build a disabled friendly toilet with running water and an exhibition centre, and to buy tools and materials for carpentry, tailoring and metal work. Every building in the centre is now disabled-friendly with the appropriate ramps, handles and other facilities. The project also comprises of a three-month awareness raising programme implemented by the local community radio station.
      </p>
      <p class="text-justify">
        In the Village of Hope, people with disabilities from many parts of Sierra Leone are involved in an apprenticeship scheme, which provides them with working skills that often allow them to return to their communities. The Village also serves as a point of contact for people with disabilities, parents of children with disabilities and the wider community.
      </p>
      <%= image_tag "wesofod-new", class: 'village-image-small d-block d-sm-none' %>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="footer-text">
    <p>
      The Welfare Society for the Disabled  •  Design by Harry Ryder
    </p>
  </div>

  <div class="footer-links">
    <a href="https://www.facebook.com/people/Wesofod-Kambia/100009048126096" target="_blank"><i class="fab fa-facebook-square icon"></i></a>

    <a href="https://www.instagram.com/wesofod/" target="_blank"><i class="fab fa-instagram icon"></i></a>

    <a href="https://twitter.com/wesofod?lang=en" target="_blank"><i class="fab fa-twitter-square icon"></i></a>

    <a href="mailto:disabilitynotinability@gmail.com" target="_blank"><i class="fas fa-envelope-square icon"></i></a>
  </div>

</div>

app/views/shared/_header.html.erb
<div class="header-large d-none d-sm-block">
  <div class="header-content">
    <%= link_to 'WESOFOD', root_path, class: 'logo' %>
    <!-- <h1 class="logo">WESOFOD</h1> -->
    <div class="header-actions hidden-xs">
      <%= link_to 'About', about_path, class: 'header-action' %>
      <%= link_to 'Village of Hope', village_path, class: 'header-action' %>
      <%= link_to 'RRC', rrc_path, class: 'header-action' %>
      <%= link_to 'Contact', contact_path, class: 'header-action' %>
    </div>
  </div>
</div>

<div class="header-large d-block d-sm-none">
  <div class="header-content">
    <%= link_to 'WESOFOD', root_path, class: 'logo' %>
    <!-- <h1 class="logo">WESOFOD</h1> -->
    <div class="header-actions-small hidden-xs">
      <div class="dropdown">
        <i class="fas fa-bars" data-toggle="dropdown" role="button"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/about">About</a></li>
          <li><a href="/village-of-hope">Village of Hope</a></li>
          <li><a href="/rrc">RRC</a></li>
          <li><a href="/contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>